Rootfs overlay

diff --git a/board/pluto/rootfs_overlay/etc/init.d/S21misc b/board/pluto/rootfs_overlay/etc/init.d/S21misc
--- a/board/pluto/rootfs_overlay/etc/init.d/S21misc
+++ b/board/pluto/rootfs_overlay/etc/init.d/S21misc
@@ -1,4 +1,12 @@
-#! /bin/sh
+#!/bin/sh
+
+LIGHTBLUE="\e[38;5;87m"
+LIGHTGREEN="\e[38;5;46m"
+LIGHTRED="\e[38;5;196m"
+NORMAL="\e[0m"
+OK="${LIGHTGREEN}OK${NORMAL}"
+FAIL="${LIGHTRED}FAIL${NORMAL}"
+HEADER="${LIGHTBLUE}[S21 misc]${NORMAL}\t"
 
 xo_correction() {
 
@@ -16,18 +24,13 @@ xo_correction() {
 
 case "$1" in
 	start|"")
-		echo -n "Starting miscellaneous setup: "
-		# Restore saved password and Dropbear keys
-		[[ -d /mnt/jffs2/etc ]] && cd /mnt/jffs2/etc && md5sum -s -c password.md5 && cp passwd shadow group /etc
-		[[ -d /mnt/jffs2/etc/dropbear ]] && cd /mnt/jffs2/etc/dropbear && md5sum -s -c keys.md5 && cp dropbear* /etc/dropbear/
-		[[ -d /mnt/jffs2/root/.ssh ]] && cd /mnt/jffs2/root/.ssh && md5sum -s -c keys.md5 && mkdir /root/.ssh && cp authorized_keys /root/.ssh
+		echo -ne "${HEADER}Starting miscellaneous setup..." > /dev/kmsg
 		xo_correction
 		MAX_BS=`fw_printenv -n iio_max_block_size 2> /dev/null || echo 67108864`
 		echo ${MAX_BS} > /sys/module/industrialio_buffer_dma/parameters/max_block_size
-		[ $? = 0 ] && echo "OK" || echo "FAIL"
+		[ $? = 0 ] && echo -e "${HEADER}started ${OK}" > /dev/kmsg || echo -e "${HEADER}start ${FAIL}" > /dev/kmsg
 		;;
 	stop)
-
 		;;
 	*)
 		echo "Usage: $0 {start|stop}" >&2
diff --git a/board/pluto/rootfs_overlay/etc/init.d/S23udc b/board/pluto/rootfs_overlay/etc/init.d/S23udc
--- a/board/pluto/rootfs_overlay/etc/init.d/S23udc
+++ b/board/pluto/rootfs_overlay/etc/init.d/S23udc
@@ -1,5 +1,13 @@
 #!/bin/sh
 
+LIGHTBLUE="\e[38;5;87m"
+LIGHTGREEN="\e[38;5;46m"
+LIGHTRED="\e[38;5;196m"
+NORMAL="\e[0m"
+OK="${LIGHTGREEN}OK${NORMAL}"
+FAIL="${LIGHTRED}FAIL${NORMAL}"
+HEADER="${LIGHTBLUE}[S23 udc]${NORMAL}\t"
+
 source /etc/device_config
 
 CONFIGFS=/sys/kernel/config/usb_gadget
@@ -60,7 +68,7 @@ create_iiod_context_attributes() {
 
 case "$1" in
   start)
-	echo -n "Starting UDC Gadgets: "
+	echo -ne "${HEADER}Starting UDC Gadgets..." > /dev/kmsg
 	mount configfs -t configfs /sys/kernel/config 2> /dev/null
 
 	mkdir -p $GADGET
@@ -110,7 +118,7 @@ case "$1" in
 		echo 500 > $GADGET/configs/c.1/MaxPower
 	fi
 
-	ln -s $GADGET/functions/$USB_NET_FUNCTION $GADGET/configs/c.1
+	ln -s $GADGET/functions/rndis.0 $GADGET/configs/c.1
 	ln -s $GADGET/functions/mass_storage.0 $GADGET/configs/c.1
 	ln -s $GADGET/functions/acm.usb0 $GADGET/configs/c.1
 	ln -s $GADGET/functions/ffs.iio_ffs $GADGET/configs/c.1/ffs.iio_ffs
@@ -123,7 +131,7 @@ case "$1" in
 
 	echo ci_hdrc.0 > $GADGET/UDC
 
-	[ $? = 0 ] && echo "OK" || echo "FAIL"
+	[ $? = 0 ] && echo -e "${HEADER}started ${OK}" > /dev/kmsg || echo -e "${HEADER}start ${FAIL}" > /dev/kmsg
 
 	if [ "$UDC_HANDLE_SUSPEND" == "1" ]; then
 		start-stop-daemon -S -b -q -m -p /var/run/udc_handle_suspend.pid -x  /sbin/udc_handle_suspend.sh
@@ -131,7 +139,7 @@ case "$1" in
 
 	;;
   stop)
-	echo "Stopping UDC Gadgets"
+	echo -ne "${HEADER}Stopping UDC Gadgets" > /dev/kmsg
 
 	if [ "$UDC_HANDLE_SUSPEND" == "1" ]; then
 		start-stop-daemon -K -q -p /var/run/udc_handle_suspend.pid 2>/dev/null
@@ -156,6 +164,7 @@ case "$1" in
 
 	rmdir $GADGET 2> /dev/null
 
+	[ $? = 0 ] && echo -e "${HEADER}stopped ${OK}" > /dev/kmsg || echo -e "${HEADER}stop ${FAIL}" > /dev/kmsg
 	;;
   restart|reload)
 	"$0" stop
diff --git a/board/pluto/rootfs_overlay/etc/init.d/S45msd b/board/pluto/rootfs_overlay/etc/init.d/S45msd
--- a/board/pluto/rootfs_overlay/etc/init.d/S45msd
+++ b/board/pluto/rootfs_overlay/etc/init.d/S45msd
@@ -1,33 +1,33 @@
 #!/bin/sh
 # Server-side demuxing by default
 
+LIGHTBLUE="\e[38;5;87m"
+LIGHTGREEN="\e[38;5;46m"
+LIGHTRED="\e[38;5;196m"
+NORMAL="\e[0m"
+OK="${LIGHTGREEN}OK${NORMAL}"
+FAIL="${LIGHTRED}FAIL${NORMAL}"
+HEADER="${LIGHTBLUE}[S45 msd]${NORMAL}\t"
+
 source /etc/device_config
 
 CONF=/opt/config.txt
 file=/sys/kernel/config/usb_gadget/composite_gadget/functions/mass_storage.0/lun.0/file
-img=/opt/vfat.img
+img=/tmp/vfat.img
 
 patch_html_page() {
 	LINUX=`uname -a | tr / - | tr '\n' ';' ; echo -n $(nproc) "core(s)"`
 	MODEL=`cat /etc/libiio.ini | grep hw_model= | cut -d '=' -f 2`
 	SERIAL=`cat /sys/kernel/config/usb_gadget/composite_gadget/strings/0x409/serialnumber`
-	MACHOST=`cat /sys/kernel/config/usb_gadget/composite_gadget/functions/*/host_addr`
-	MAC=`cat /sys/kernel/config/usb_gadget/composite_gadget/functions/*/dev_addr`
-	IIO=`iio_info -V 2>/dev/null | tail -1`
+	MACHOST=`cat /sys/kernel/config/usb_gadget/composite_gadget/functions/rndis.0/host_addr`
+	MAC=`cat /sys/kernel/config/usb_gadget/composite_gadget/functions/rndis.0/dev_addr`
+	IIO=`iio_info 2>/dev/null | grep "Library version:"`
 	BUILD=`grep device-fw /opt/VERSIONS | cut -d ' ' -f 2`
 	FPGA=`grep hdl /opt/VERSIONS | cut -d ' ' -f 2`
 	ROOTFS=`grep buildroot /opt/VERSIONS | cut -d ' ' -f 2`
 	UBOOT=`cat /proc/cmdline | tr  "=" "\n" | grep "U-Boot"`
-	USB_ETH_MODE=`fw_printenv -n usb_ethernet_mode 2> /dev/null || echo rndis`
-	if [ "$USB_ETH_MODE" == "ncm" ]; then
-		NETWORKUSB="Communications Device Class – Network Control Model (CDC-NCM)"
-	elif [ "$USB_ETH_MODE" == "ecm" ]; then
-		NETWORKUSB="Communications Device Class – Ethernet Control Module (CDC-EMC)"
-	else
-		NETWORKUSB="Remote Network Driver Interface Specification (RNDIS)"
-	fi
 
-	sed -i -e "s/#LINUX#/$LINUX/g" -e "s/#MODEL#/$MODEL/g" -e "s/#SERIAL#/$SERIAL/g" -e "s/#MACHOST#/$MACHOST/g" -e "s/#MAC#/$MAC/g" -e "s/#IIO#/$IIO/g" -e "s/#BUILD#/$BUILD/g" -e "s/#FPGA#/$FPGA/g" -e "s/#ROOTFS#/$ROOTFS/g" -e "s/#UBOOT#/$UBOOT/g" -e "s/#NETWORKUSB#/$NETWORKUSB/g" $1
+	sed -i -e "s/#LINUX#/$LINUX/g" -e "s/#MODEL#/$MODEL/g" -e "s/#SERIAL#/$SERIAL/g" -e "s/#MACHOST#/$MACHOST/g" -e "s/#MAC#/$MAC/g" -e "s/#IIO#/$IIO/g" -e "s/#BUILD#/$BUILD/g" -e "s/#FPGA#/$FPGA/g" -e "s/#ROOTFS#/$ROOTFS/g" -e "s/#UBOOT#/$UBOOT/g" $1
 
 	sed -i -e "s/#BUILD#/$BUILD/g" $2 /etc/motd
 }
@@ -35,32 +35,34 @@ patch_html_page() {
 
 case "$1" in
 	start)
-		echo -n "Starting MSD Daemon: "
-		patch_html_page /www/index.html /www/img/version.js
-		losetup /dev/loop7 $img -o 512
-		mount /dev/loop7 /mnt/msd
+		echo -ne "${HEADER}Starting MSD Daemon..." > /dev/kmsg
+		patch_html_page "/www/index.html /www/img/index_*.html" /www/img/version.js
+        dd if=/dev/zero of=$img bs=1M seek=30 count=0
+        mkfs.vfat -n "${MODEL}" $img
+		mount $img /mnt
 
 		if [ "$TARGET" == "m2k" ]; then
 			cp /opt/${CALIBFILENAME} /mnt
-			md5sum /mnt/msd/${CALIBFILENAME} > /opt/${CALIBFILENAME}.md5
+			md5sum /mnt/${CALIBFILENAME} > /opt/${CALIBFILENAME}.md5
 		fi
 
-		cp $CONF /mnt/msd
-		md5sum /mnt/msd/config.txt > /opt/config.md5
+		cp $CONF /mnt
+		md5sum /mnt/config.txt > /opt/config.md5
 
-		cp -a /www/* /mnt/msd
-		mv /mnt/msd/index.html /mnt/msd/info.html
-		umount /mnt/msd
+		cp -a /www/* /mnt/
+		mv /mnt/index.html /mnt/info.html
+		sed -i -e "s/..\/index.html/..\/info.html/g" /mnt/img/index_*.html
+		umount /mnt
 		echo $img > $file
 
 		start-stop-daemon -S -b -q -m -p /var/run/update.pid -x /bin/sh -- /sbin/update.sh
-		[ $? = 0 ] && echo "OK" || echo "FAIL"
+		[ $? = 0 ] && echo -e "${HEADER}started ${OK}" > /dev/kmsg || echo -e "${HEADER}start ${FAIL}" > /dev/kmsg
 		;;
 
 	stop)
-		echo -n "Stopping MSD Daemon: "
+		echo -ne "${HEADER}Stopping MSD Daemon..." > /dev/kmsg
 		start-stop-daemon -K -q -p /var/run/update.pid 2>/dev/null
-		[ $? = 0 ] && echo "OK" || echo "FAIL"
+		[ $? = 0 ] && echo -e "${HEADER}stopped ${OK}" > /dev/kmsg || echo -e "${HEADER}stop ${FAIL}" > /dev/kmsg
 		;;
 
 	restart)
